PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX graphs: <http://mu.semte.ch/graphs/>
PREFIX eurostat: <http://data.europa.eu/eurostat/>

INSERT DATA {
 GRAPH <http://mu.semte.ch/graphs> {

  eurostat:ECOICOP a graphs:Graph.
  graphs:ECOICOPs a graphs:GraphRule;
                 graphs:subjectType skos:Concept;
                 graphs:graph eurostat:ECOICOP .

  graphs:ScannerData a graphs:GraphType.
  graphs:SD a graphs:GraphRule;
           graphs:predicate mu:category;
           graphs:graphType graphs:ScannerData.

  eurostat:AlbertHeijn a graphs:Graph;
                       graphs:type graphs:ScannerData;
                       graphs:realm "AlbertHeijn".

  eurostat:Lidl a graphs:Graph;
                       graphs:type graphs:ScannerData;
                       graphs:realm "Lidl"
  }

  GRAPH eurostat:ECOICOPS {
        eurostat:ECOICOP1 a skos:Concept.
        eurostat:ECOICOP2 a skos:Concept.
        eurostat:ECOICOP3 a skos:Concept.
  }

 GRAPH eurostat:ids {
       eurostat:ECOICOP1 mu:uuid "ecoicop1".
       eurostat:ECOICOP2 mu:uuid "ecoicop2".
       eurostat:ECOICOP3 mu:uuid "ecoicop3".
 }

  GRAPH eurostat:Lidl {
        eurostat:product1 a eurostat:Product;
                          mu:category eurostat:ECOICOP1.
        eurostat:product2 a eurostat:Product;
                          mu:category eurostat:ECOICOP2.
  }

  GRAPH eurostat:AlbertHeijn {
        eurostat:product3 a eurostat:Product;
                          mu:category eurostat:ECOICOP3.
  }

}